# Usuarios #
###
GET https://projeto-final-rkig.onrender.com/ping

###
POST https://projeto-final-rkig.onrender.com/users/signup
Content-Type: application/json

{
  "name":"larina",
  "email":"larina@gmail.com",
  "password":"casdfeisar"
}

###
POST http://localhost:3003/users/Login
Content-Type: application/json 

{
  "email": "larina@gmail.com",
  "password":"casdfeisar"
}

# Postagens #

###
POST http://localhost:3003/postagens
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZkOWZkOWVjLTA5ZTEtNDFhNC04ZTVlLTgyNDRjODcyZTJjZCIsIm5hbWUiOiJsYXJpbmEiLCJyb2xlIjoiTk9STUFMIiwiaWF0IjoxNjkyOTExNDU1LCJleHAiOjE2OTM1MTYyNTV9.8tC_OV6_soDhjmYjFt0h5e-VAoLBd8Gudet0WYNQDOk

{
  "name":"manchetes"
}

###
GET http://localhost:3003/postagens
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZkOWZkOWVjLTA5ZTEtNDFhNC04ZTVlLTgyNDRjODcyZTJjZCIsIm5hbWUiOiJsYXJpbmEiLCJyb2xlIjoiTk9STUFMIiwiaWF0IjoxNjkyOTExNDU1LCJleHAiOjE2OTM1MTYyNTV9.8tC_OV6_soDhjmYjFt0h5e-VAoLBd8Gudet0WYNQDOk

###
PUT http://localhost:3003/postagens/dc9d8964-0bc2-4bcf-bcd7-8e4efa3c6ea0
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZkOWZkOWVjLTA5ZTEtNDFhNC04ZTVlLTgyNDRjODcyZTJjZCIsIm5hbWUiOiJsYXJpbmEiLCJyb2xlIjoiTk9STUFMIiwiaWF0IjoxNjkyOTExNDU1LCJleHAiOjE2OTM1MTYyNTV9.8tC_OV6_soDhjmYjFt0h5e-VAoLBd8Gudet0WYNQDOk

{
  "conteudo":"Vamao que vamo rapaziada da Labenu"
}

###
PUT http://localhost:3003/postagens/dc9d8964-0bc2-4bcf-bcd7-8e4efa3c6ea0/like
Content-Type:application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZkOWZkOWVjLTA5ZTEtNDFhNC04ZTVlLTgyNDRjODcyZTJjZCIsIm5hbWUiOiJsYXJpbmEiLCJyb2xlIjoiTk9STUFMIiwiaWF0IjoxNjkyOTExNDU1LCJleHAiOjE2OTM1MTYyNTV9.8tC_OV6_soDhjmYjFt0h5e-VAoLBd8Gudet0WYNQDOk

{
  "like":true
}

###
DELETE http://localhost:3003/postagens/dc9d8964-0bc2-4bcf-bcd7-8e4efa3c6ea0
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZkOWZkOWVjLTA5ZTEtNDFhNC04ZTVlLTgyNDRjODcyZTJjZCIsIm5hbWUiOiJsYXJpbmEiLCJyb2xlIjoiTk9STUFMIiwiaWF0IjoxNjkyOTExNDU1LCJleHAiOjE2OTM1MTYyNTV9.8tC_OV6_soDhjmYjFt0h5e-VAoLBd8Gudet0WYNQDOk