# Usuarios #
###
GET http://localhost:3003/ping

###
POST http://localhost:3003/users/signup
Content-Type: application/json

{
  "apelido":"larina",
  "email":"larina@gmail.com",
  "password":"casdfeisar"
}

###
POST http://localhost:3003/users/Login
Content-Type: application/json 

{
  "email": "larina@gmail.com",
  "password":"casdfeisar"
}

# Postagens #

###
POST http://localhost:3003/postagens
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkMTZhMzRmLTY2MWItNGE5My05N2E0LTdiZTc0MmUzYjlkNyIsImFwZWxpZG8iOiJsYXJpbmEiLCJyb2xlIjoiTk9STUFMIiwiaWF0IjoxNjkwNTAwOTY4LCJleHAiOjE2OTExMDU3Njh9.eWgXxPWngR0yzZ3sXPlbMbVsHXWt9nTvtzRaGETJWbw

{
  "apelido":"manchetes"
}

###
GET http://localhost:3003/postagens
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkMTZhMzRmLTY2MWItNGE5My05N2E0LTdiZTc0MmUzYjlkNyIsImFwZWxpZG8iOiJsYXJpbmEiLCJyb2xlIjoiTk9STUFMIiwiaWF0IjoxNjkwNTAwOTY4LCJleHAiOjE2OTExMDU3Njh9.eWgXxPWngR0yzZ3sXPlbMbVsHXWt9nTvtzRaGETJWbw

###
PUT http://localhost:3003/postagens/cad4cead-f41e-43b2-bf17-00673582884c
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkMTZhMzRmLTY2MWItNGE5My05N2E0LTdiZTc0MmUzYjlkNyIsImFwZWxpZG8iOiJsYXJpbmEiLCJyb2xlIjoiTk9STUFMIiwiaWF0IjoxNjkwNTAwOTY4LCJleHAiOjE2OTExMDU3Njh9.eWgXxPWngR0yzZ3sXPlbMbVsHXWt9nTvtzRaGETJWbw

{
  "conteudo":"Vamao que vamo rapaziada da Labenu"
}

###
PUT http://localhost:3003/postagens/8e39c3bd-d5c9-4945-8014-5a4e1c958589/like
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkMTZhMzRmLTY2MWItNGE5My05N2E0LTdiZTc0MmUzYjlkNyIsImFwZWxpZG8iOiJsYXJpbmEiLCJyb2xlIjoiTk9STUFMIiwiaWF0IjoxNjkwNTAwOTY4LCJleHAiOjE2OTExMDU3Njh9.eWgXxPWngR0yzZ3sXPlbMbVsHXWt9nTvtzRaGETJWbw

{
  "like":false
}

###
DELETE http://localhost:3003/postagens/8e39c3bd-d5c9-4945-8014-5a4e1c958589
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkMTZhMzRmLTY2MWItNGE5My05N2E0LTdiZTc0MmUzYjlkNyIsImFwZWxpZG8iOiJsYXJpbmEiLCJyb2xlIjoiTk9STUFMIiwiaWF0IjoxNjkwNTAwOTY4LCJleHAiOjE2OTExMDU3Njh9.eWgXxPWngR0yzZ3sXPlbMbVsHXWt9nTvtzRaGETJWbw